# Generated by Django 5.1.7 on 2025-03-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='designation',
            field=models.CharField(max_length=200),
        ),
    ]
