services:

  db:
    image: postgres:13-alpine
    container_name: myapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432

  web:
    image: alija10/notes-app:latest
    container_name: myapp_web
    env_file:
      - .env
    build: .
    restart: always
    volumes:
      - .:/myapp
    depends_on:
      - db
    ports:
      - 8001:8000
    

  pgadmin:
    container_name: myapp_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test
      - PGADMIN_CONFIG_SERVER_MODE=False
    
    ports:
      - "5052:80"
    depends_on:
      - db
    volumes:
      - pgadmindata:/var/lib/pgadmin


volumes:
  pgadmindata:
  postgres_data:
