name: CD - Deploy Application

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]   # Runs after CI
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Latest Docker Image
        run: |
          docker pull alija10/notes-app:latest

      - name: Stop and Remove Existing Containers
        run: |
          docker-compose -f ../../docker-compose.yml down || true     
      - name: Start Application
        run: |
          docker-compose -f ../../docker-compose.yml up -d
      - name: Reload Nginx
        run: |
          sudo nginx -s reload

      - name: Check Docker Containers Status
        run: |
          docker ps

      - name: View Docker Compose Logs
        run: |
          docker-compose -f ../../docker-compose.yml logs -f

