name: CD - Deploy Application

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]   # Runs after CI
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    
    
      - name: Pull Latest Docker Image
        run: |
          echo "Pulling latest docker image"
          sudo docker pull alija10/notes-app:latest

      - name: Stop and Remove Existing Containers
        run: |
          sudo docker-compose down || true     
     
      - name: Start Application
        run: |
          sudo docker-compose up -d 
          sudo docker-compose logs
  
      - name: Reload Nginx
        run: |
          sudo nginx -s reload

      - name: Check Docker Containers Status
        run: |
          sudo docker ps


