name: CD - Deploy Application

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]   # Runs after CI
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    
    
      - name: Pull Latest Docker Image
        run: |
          echo "Pulling latest docker image"
          sudo docker pull alija10/notes-app:latest

      - name: Stop and Remove Existing Containers
        run: |
          sudo docker-compose down || true   
          # Ensure all related containers are removed
          existing_containers=$(sudo docker ps -aq --filter "name=myapp_")
          if [ -n "$existing_containers" ]; then
            sudo docker rm -f $existing_containers
          fi
     
      - name: Start Application with Updated Image
        run: |
          # Force update the 'web' service to use the new image
          sudo docker-compose up -d --force-recreate --no-deps web
          sudo docker-compose up -d pgadmin db  # Start other services
          sudo docker-compose logs
  
      - name: Reload Nginx
        run: |
          sudo nginx -s reload

      - name: Check Docker Containers Status
        run: |
          sudo docker ps


